version: '3'

services:
  db:
    image: mysql:5.7.21
    container_name: bookstack_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: bookstack
      MYSQL_USER: bookstack
      MYSQL_PASSWORD: secret
      TZ: UTC
    volumes:
      - db_data:/var/lib/mysql

  bookstack:
    image: solidnerd/bookstack:22.04
    container_name: bookstack_app
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DB_HOST: bookstack_db:3306
      DB_DATABASE: bookstack
      DB_USERNAME: bookstack
      DB_PASSWORD: secret
      APP_URL: http://192.168.125.221:8681
      TZ: UTC
    expose:
      - "8080"

  nginx:
    image: nginx:latest
    container_name: bookstack_nginx
    restart: unless-stopped
    ports:
      - "8681:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - bookstack

volumes:
  db_data:
